- name: setup repository
  shell: rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
  register: result
  failed_when: result.rc not in [0, 1, 130]
  tags: install

- name: add mysql community server repository
  yum: name="{{ item }}" state=present
  with_items:
    - http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - mysql-community-server
  tags: install

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
  tags: install

