- name: save original configuration files
  copy: src=/etc/ansible/template/ldap-client/{{ item }}
        dest=/etc/{{ item }}
  with_items:
    - openldap/ldap.conf
    - pam.d/system-auth
    - nsswitch.conf
    - pam_ldap.conf
  tags: config

- name: do authconfig
  shell: authconfig --enableldap --enableldapauth --ldapserver="ldap://172.0.0.20/" --ldapbasedn="dc=wara,dc=local" --enablemkhomedir --update
