- name: install zabbix agent
  shell: rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
  register: result
  failed_when: result.rc not in [0, 1, 130]
  tags: install

- name: install package
  yum: name=zabbix-agent
       state=present
  tags: install
