# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos6.6-minimal"

  config.vm.define :server do |server|
      server.vm.hostname = "ldap-server"
      server.vm.network :private_network, ip: "172.0.0.20", virtualbox__intnet: "intnet"
  end

  config.vm.define :client1 do |client1|
      client1.vm.hostname = "ldap-client1"
      client1.vm.network :private_network, ip: "172.0.0.30", virtualbox__intnet: "intnet"
  end

  config.vm.define :client2 do |client2|
      client2.vm.hostname = "ldap-client2"
      client2.vm.network :private_network, ip: "172.0.0.40", virtualbox__intnet: "intnet"
  end
end

